services:
  web:
    image: bookit:latest
    build: 
      context: .
      dockerfile: HotelReservationSystem.Web/Dockerfile
    container_name: bookit_web
    ports:
      - "8081:80"
    networks:
      - bookit-tests
    environment:
      - ConnectionStrings__DefaultConnection=${CONN_STRING}
      - ConnectionStrings__Redis=redis:6379
      - OpenAI__ApiKey=${OPENAI_API_KEY} 
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - bookit-tests
    env_file:
      - .env
    container_name: bookit_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_test_data:/var/opt/mssql/tests
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $${SQL_PASSWORD} -Q \"SELECT 1\" > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: bookit_redis
    ports:
      - "6380:6379"
    networks:
      - bookit-dev
    volumes:
      - redis_test_data:/data

networks:
  bookit-tests:
    name: bookit-tests-network
    driver: bridge

volumes:
  sqlserver_test_data:
  redis_test_data: