networks:
  bookit-prod:
    name: bookit-network
    driver: bridge

volumes:
  sqlserver_data:
  redis_data:

services:
  web:
    image: bookit:latest 
    networks:
      - bookit-prod

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks: 
      - bookit-prod
  
  redis:
    image: redis:7-alpine
    networks:
      - bookit-prod

  workers:
    image: bookit-workers:latest
    networks:
      - bookit-prod
