services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - bookit-dev
    env_file:
      - .env
    container_name: bookit_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_dev_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $${SQL_PASSWORD} -Q \"SELECT 1\" > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: bookit_redis
    ports:
      - "6379:6379"
    networks:
      - bookit-dev
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  bookit-dev:
    name: bookit-dev-network
    driver: bridge

volumes:
  sqlserver_dev_data:
  redis_dev_data: