services:
  web-tests:
    image: bookit:latest
    build: 
      context: ./HotelReservationSystem
      dockerfile: HotelReservationSystem.Web/Dockerfile
    container_name: bookit_web
    ports:
      - "8081:80"
    networks:
      - bookit-tests
    environment:
      - ConnectionStrings__DefaultConnection=${CONN_STRING}
      - ConnectionStrings__Redis=redis-tests:6379 
      - ConnectionStrings__AzureStorage=${QUEUE_PARAMS}
      - OpenAI__Endpoint=http://ollama-tests:11434/v1 
      - OpenAI__ModelId=llama3.2:latest 
    depends_on:
      sqlserver-tests: 
        condition: service_healthy
      redis-tests: 
        condition: service_healthy
      azurite-tests: 
        condition: service_started

  sqlserver-tests:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks:
      - bookit-tests
    env_file:
      - .env
    container_name: bookit_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_test_data:/var/opt/mssql/tests
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $${SQL_PASSWORD} -Q \"SELECT 1\" > /dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  redis-tests:
    image: redis:7-alpine
    container_name: bookit_redis
    ports:
      - "6380:6379"
    networks:
      - bookit-tests
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ollama-tests:
    container_name: bookit_ollama
    image: ollama/ollama:latest
    ports:
      - "11435:11434" 
    networks:
      - bookit-tests
    volumes:
      - ~/.ollama:/root/.ollama
    restart: unless-stopped

  azurite-tests:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: bookit_azurite
    ports:
      - "10001:10001" 
    networks:
      - bookit-tests
    command: "azurite --queueHost 0.0.0.0 --queuePort 10001"

networks:
  bookit-tests:
    name: bookit-tests-network
    driver: bridge

volumes:
  sqlserver_test_data:
  redis_test_data:
